"use strict";
const _imports_0$3 = "/static/school/school-logo-377x378.png";
const _imports_1 = "/static/school/school-motto-810x134.png";
const _imports_2 = "/static/school/school-library-579x299.png";
const _imports_0$2 = "/static/school/schoolbg-1920x1084.jpg";
const _imports_0$1 = "/static/images/avatar.jpg";
const _imports_0 = "/static/tabbar/scan.png";
exports._imports_0 = _imports_0;
exports._imports_0$1 = _imports_0$3;
exports._imports_0$2 = _imports_0$2;
exports._imports_0$3 = _imports_0$1;
exports._imports_1 = _imports_1;
exports._imports_2 = _imports_2;
